### ISSUE TITLE
Doesn't work as an AMD module with RequireJS/Almond

### ISSUE THREAD

**Issue by c24w** [smnh/FontLoader#14]
FontLoader seems to have this problem: https://github.com/jrburke/almond#incorrect-module-build-no-module-name

**Comment by smnh** [comment]
Hi @c24w,
As written in the almond's file, I guess that the tool you use to combine your JavaScript files does not add the module name to FontLoader.
From my experience, it is better not to specify module names inside the library itself. But configure the build tool (like r.js) to name the modules according to the `path` configurations.

**Comment by c24w** [comment]
Thanks @smnh.  I was trying to load the script alongside some built AMD modules, rather than as part of the bundle, which I guess is probably not typical usage.  I'll try something else :)
