### ISSUE TITLE
The message object doesn't update

### ISSUE THREAD

**Issue by danail-vasilev** [smnh/FontLoader#15]
Hi Guys,

This widget looks great but the complete event always shows the error:

- "Not all fonts were loaded (0/n)"
- notLoadedFonts: Array[0]}

The above doesn't change with the properly or wrongly loaded fonts. Only n - the number of the fonts. This relates to the provided example as well

**Comment by smnh** [comment]
Hi @danail-vasilev,

Could you please elaborate on the way you are trying to load your fonts? The OS and the browser version you are using. And also the type of the fonts. Are these some special kind of fonts? A code snippet might help.

**Comment by danail-vasilev** [comment]
Hi @smnh,

I have just downloaded the example from this repository - FontLoader-master.zip (http://screencast.com/t/CSofJ6Gr) and run it.

The console of the browser (latest FireFox, Chrome and IE) always show the error message and that all the fonts are not loaded in the error object - http://screencast.com/t/lDRX9JOeSxv4

OS is Windows 8.1

**Comment by smnh** [comment]
Hi @danail-vasilev,

Indeed there was a bug that was caused but the latest refactoring after the addition of the font variation feature. Pushed the fix.

Thank you for pointing out on this issue.

**Comment by danail-vasilev** [comment]
Hi @smnh,

Thank you for looking into that ! I will try the latest version.

Kind Regards,
Danail
