### ISSUE TITLE
IE11 bug

### ISSUE THREAD

**Issue by clemensmol** [smnh/FontLoader#18]
FontLoader doesn't work in IE 11 because of wrong useragent detection. To detect IE11 you need to look for "Trident" in the user agent, not "MSIE".

/Trident/i.test(navigator.userAgent)

and version number regex:
var re=new RegExp("Trident/.*rv:([0-9]{1,}[\.0-9]{0,})");

**Comment by smnh** [comment]
IE11 detection is not an issue, because on IE11, both scroll events, and AdobeBlank font are working as expected (I've just tested it). So it is actually a good thing that IE11 is treated as not an IE browser. Moreover, there are these checks that would fail for correct IE11 detection anyway:

    FontLoader.useAdobeBlank = !isIE || ieVer >= 11.0;
    FontLoader.useResizeEvent = isIE && ieVer < 11.0 && typeof document.attachEvent !== "undefined";
